
// #define TRI_LAYER_LOWER_LAYER 1
// #define TRI_LAYER_UPPER_LAYER 2
// #define TRI_LAYER_ADJUST_LAYER 3

// #ifdef TAPPING_TOGGLE
// #undef TAPPING_TOGGLE
// #define TAPPING_TOGGLE 2
// #endif

// #ifdef ONESHOT_TAP_TOGGLE
// #undef ONESHOT_TAP_TOGGLE
// #define ONESHOT_TAP_TOGGLE 2
// #endif

// #define TAPPING_TERM 200

#ifdef ENCODER_RESOLUTION 
#undef ENCODER_RESOLUTION 
#define ENCODER_RESOLUTION 4
#endif

#define OLED_BRIGHTNESS 32
#define OLED_TIMEOUT 30000
