
// #define TRI_LAYER_LOWER_LAYER 1
// #define TRI_LAYER_UPPER_LAYER 2
// #define TRI_LAYER_ADJUST_LAYER 3

// #ifdef TAPPING_TOGGLE
// #undef TAPPING_TOGGLE
// #define TAPPING_TOGGLE 2
// #endif

// #ifdef ONESHOT_TAP_TOGGLE
// #undef ONESHOT_TAP_TOGGLE
// #define ONESHOT_TAP_TOGGLE 2
// #endif

// #define TAPPING_TERM 200

// POINTING_DEVICE_ENABLE = yes
// POINTING_DEVICE_DRIVER = analog_joystick
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define ANALOG_JOYSTICK_X_AXIS_PIN	F4
#define ANALOG_JOYSTICK_Y_AXIS_PIN	F5
